# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 13:50
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models
import stdimage.utils
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIFEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('gif_file', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='gifs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif'])])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_entries', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'gif entry',
                'verbose_name_plural': 'gif entries',
            },
        ),
    ]
